[build]
    publish = "site"
    functions = "functions"

[dev]
    autoLaunch=false

[functions]
    [functions.main]
        included_files = ["templates/main.hbs"]


[[redirects]]
    from = "/gallery"
    to = "/.netlify/site/gallery.html"
    status = 200
